[package]
name = "moai"
version = "0.1.0"
authors = ["Victor Palade <victor.palade@cloudflavor.io>"]
edition = "2018"

[dependencies]
libvirt = "0.1.0"
clap = "2.33.0"
config = "0.9.3"
serde = "1.0.98"
serde_derive = "1.0.99"
log = "0.4.8"
env_logger = "0.6.2"